### ISSUE TITLE
Add possibility of plotting theoretical ACF/PACF

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/simts#10]
See exts for details. Here is an example:

<img width="591" alt="screen shot 2017-09-08 at 5 55 04 pm" src="https://user-images.githubusercontent.com/9849320/30232723-8e19c7b2-94bf-11e7-8c22-31711af107e6.png">

Experimental Time Series Features - Scroll to RACF PACF

**Comment by munsheet** [comment]
I think this is done?
