### ISSUE TITLE
Compatibility of legends in make_frame

### ISSUE THREAD

**Issue by Yuming-Zhang** [SMAC-Group/simts#11]
Hi,

I think make_frame works very well when we add plots on it. The only issue I find out for this moment is that, make_frame seems to have some issue with the location of legend of the original plot.

For example, please try the below code:
Xt = gen_gts(300, AR(phi = c(0, 0, 0.8), sigma2 = 1))
model = arima(Xt, order = c(3,0,0), include.mean = T)
resid_plot(Xt, model, std = FALSE, type = "hist")

As you can see the plot will have legend in the very topright, which should be included inside the white space.

@munsheet Do you think we can modify the make_frame function a bit to have it compatible with legends? Please let me know if I can help in any way! Thanks a lot! :)

**Comment by munsheet** [comment]
lgd = legend(x = mean(c(par("usr")[1],par("usr")[2])), 
                  y =  mean(c(par("usr")[3],par("usr")[4])),
                  legend = c("Kernel", "Normal"), 
                  text.col = c("blue", "black"),
                  bty = "n",
                  cex = 0.8,
                  plot = F)
    
    # Plot on top right 
    legend(x = par("usr")[2] - lgd$rect$w, 
           y =  par("usr")[4] - lgd$rect$h,
           legend = c("Kernel", "Normal"), 
           text.col = c("blue", "black"),
           bty = "n",
           cex = 0.8, 
           plot = T)

**Comment by munsheet** [comment]
custom_legend() should work the same as legend() 

Try running the above lines again. 

Xt = gen_gts(300, AR(phi = c(0, 0, 0.8), sigma2 = 1))
model = arima(Xt, order = c(3,0,0), include.mean = T)
resid_plot(Xt, model, std = FALSE, type = "hist")

I replaced all legend() with custom_legend()
